import HomePage from "@/modules/home";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Travel Pulse - Best Travel Experience",
  description: "Generated by create next app",
};

export default function Home() {
  return <HomePage />;
}
