import Hero from "@/modules/destination/(detailPage)/components/Hero";
import LatestFeatured from "@/modules/destination/(detailPage)/components/LatestFeatured";
import OtherPlaces from "@/modules/destination/(detailPage)/components/OtherPlaces";
import ShortDescription from "@/modules/destination/(detailPage)/components/ShortDescription";
import TopSights from "@/modules/destination/(detailPage)/components/TopSights";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Croatia - Travel Pulse",
  description: "Generated by create next app",
};

export default function DetailPage() {
  return (
    <>
      <Hero />
      <ShortDescription />
      <TopSights />
      <LatestFeatured />
      <OtherPlaces />
    </>
  );
}
