import DestinationPage from "@/modules/destination";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Destination - Travel Pulse",
  description: "Generated by create next app",
};

export default function Destination() {
  return <DestinationPage />;
}
