import RegisterPage from "@/modules/auth/register";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Register - Travel Pulse",
  description: "Generated by create next app",
};

export default function SignUp() {
  return <RegisterPage />;
}
